### ISSUE TITLE
Getting error when trying to create a repgen project.

### ISSUE THREAD

**Issue by joannejinshao** [jdeering/visor#4]
Hi, thanks a lot for creating this extension!

I'm seeing the below error when trying to create a new repgen project:
<entry>
    <record>1186</record>
    <time>2015/11/24 19:44:34.836</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [VisorPackage]</description>
    <guid>{B06DD064-A1CA-4C34-8411-7BA23013C31F}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

Any ideas?

**Comment by jasondeering** [comment]
Which version of Visual Studio are you using? My guess is that recent updates to include support for Visual Studio 2015 may have broken older versions.

**Comment by jdeering** [comment]
Which version of Visual Studio are you using? My guess is that recent updates to include support for Visual Studio 2015 may have broken older versions.

**Comment by joannejinshao** [comment]
Your guess is correct. I was still using Visual Studio 2013.
I upgraded to VS 2015, and it is working now.

Thank you for your great work!
